pipeline:
  build:
    image: node:lts-hydrogen
    environment:
      - NODE_ENV=production
    commands:
      - ls
      - npm install
      - ls node_modules
      - npm run build

branches:
  include: [ main, feature/* ]