pipeline:
  build:
    image: node:lts-hydrogen
    # environment:
    #   - NODE_ENV=production
    commands:
      - ls
      - npm install
      - ls node_modules
      - npm run build
  deploy:
  image:
    name: gcr.io/kaniko-project/executor:debug
    commands:
      - ls
branches:
  include: [ main, feature/* ]