pipeline:
  build:
    image: node:18-alpine
    environment:
      - NODE_ENV=production
    commands:
      - ls
      - npm install
      - ls
      - npm run build

branches:
  include: [ main, feature/* ]