pipeline:
  build:
    image: node
    environment:
      - NODE_ENV=production
    commands:
      - npm install
      - npm build
  deploy:
  commands:
  - ls


branches:
  include: [ main, feature/* ]

# when:
#   tag: v*